services:
  neo4j:
    image: neo4j:2026.07.1
    container_name: codebase_graph_db
    ports:
      - "7474:7474"  # Web UI
      - "7687:7687"  # Bolt Protocol (Python connection)
    environment:
      NEO4J_AUTH: "neo4j/gladline"
      NEO4J_PLUGINS: '["graph-data-science"]'
      NEO4J_dbms_security_procedures_allowlist: "gds.*"
      NEO4J_dbms_security_procedures_unrestricted: "gds.*"
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:
